In [1]:
#1
import numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
#2
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#3
import numpy as np
b = np.array(range(10,50))
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#4
import numpy as np
d = np.array(range(0,25)).reshape((5,5))
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
#5
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
#6
import numpy as np
import random
f = np.array(random.sample(range(1,26),25)).reshape((5,5))
print(f.max())
print(f.min())

25
1


In [7]:
#7
g = np.matrix(np.full((4,3),1))
h = np.matrix(random.sample(range(1,7),6)).reshape(3,2)
print('g:',g)
print('h:',h)
g*h

g: [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
h: [[3 4]
 [1 2]
 [5 6]]


matrix([[ 9, 12],
        [ 9, 12],
        [ 9, 12],
        [ 9, 12]])

In [8]:
#8
print('matrix: ',g.transpose())
print('matrix: ',h.transpose())

matrix:  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
matrix:  [[3 1 5]
 [4 2 6]]


In [9]:
#9
import numpy as np
i = np.matrix(range(0, 25)).reshape(5,5)
j = np.matrix(range(25,50)).reshape(5,5)
print('add two mat :',i + j)
print('subtract two mat :',i - j)

add two mat : [[25 27 29 31 33]
 [35 37 39 41 43]
 [45 47 49 51 53]
 [55 57 59 61 63]
 [65 67 69 71 73]]
subtract two mat : [[-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]
 [-25 -25 -25 -25 -25]]


Q1~6 

In [10]:
#Q1
import numpy.linalg as LA
a1_1 = np.array([[1,2],[3,4]])
a1_2 = np.array([[1,2],[3,4],[5,6]])

print(LA.eig(a1_1))
try:
    print(LA.eig(a1_2)) # Last 2 dimensions of the array must be square
except:
    print('\nLA.eig(a1_2) : Last 2 dimensions of the array must be square\n\n')
print(LA.svd(a1_1, full_matrices = True))
print(LA.svd(a1_1, full_matrices = False))
print(LA.svd(a1_2, full_matrices = True))
print(LA.svd(a1_2, full_matrices = False))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

LA.eig(a1_2) : Last 2 dimensions of the array must be square


(array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
(array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), array([5.4649857 , 0.36596619]), array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
(array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]]), array([9.52551809, 0.51430058]), array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]]))
(array([[-0.2298477 ,  0.88346102],
       [-0.52474482,  0.24078249],
       [-0.81964194, -0.40189603]]), array([9.52551809, 0.51430058]), array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]]))


In [11]:
#Q2
a2 = np.array([[7,1],[1,7]])
x,y = LA.eig(a2)
x,y
'''
x는 eigen value
y는 eigen vector로
각각 scale변환,
방향을 의미한다.'''

'\nx는 eigen value\ny는 eigen vector로\n각각 scale변환,\n방향을 의미한다.'

In [12]:
#Q3
a3 = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,2,0,4,4],[0,0,0,5,5],[0,1,0,2,2]])
U,S,V = LA.svd(a3, full_matrices = False)
U,S,V
'''
U는 rotation
S는 scale 변환값
V는 rotation'''

'\nU는 rotation\nS는 scale 변환값\nV는 rotation'

In [13]:
#Q4
a4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
#A의 코드
a4_1 = a4.reshape(3,2,3)
a4_1
#B의 코드
for i in a4_1:
    for j in i:
        print(j)
        print('----')

[1 2 3]
----
[4 5 6]
----
[7 8 9]
----
[10 11 12]
----
[13 14 15]
----
[16 17 18]
----


In [14]:
#Q5
a5 = np.array([[1,2],[3,4]])
b5 = np.array([[1,3],[2,4]])
print('dot',np.dot(a5,b5))
print('*',a5*b5)
'''
np.dot은 내적
*은 같은 행렬 각 원소의 곱'''

dot [[ 5 11]
 [11 25]]
* [[ 1  6]
 [ 6 16]]


In [21]:
#Q6-1
a6_1 = np.zeros((5,5))
a6_1 += np.array(5)
a6_1

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [30]:
#Q6-2

a6_2 = np.full((4,5,3),3)
#np.cov(a6_2) # has more than 2 dimensions
a6_2

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])